apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    app: devops-app 
spec:
  selector:
    app: devops-app

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
