apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emartapp

bases:
  - ../../base

patches:
  - path: replicas-patch.yaml
  - path: resource-patch.yaml

images:
  - name: backend
    newTag: latest
  - name: frontend
    newTag: latest 