apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emartapp

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: resource-patch.yaml

images:
  - name: backend
    newTag: latest
  - name: frontend
    newTag: latest 
