apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database-config.yaml
  - database-pvc.yaml
  - database-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - service.yaml
  - network-policy.yaml
  - pod-security-policy.yaml

images:
  - name: backend
    newName: ${DOCKER_REGISTRY}/emartapp-backend
    newTag: ${BUILD_NUMBER}
  - name: frontend
    newName: ${DOCKER_REGISTRY}/emartapp-frontend
    newTag: ${BUILD_NUMBER} 